name: 'Terraform'

on:
  push:
    branches:
    - master
    - v*
    - borked-build

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Write Credentials file
      run: echo $GOOGLE_CREDENTIALS > gcloud.key
      env:
        PROJECT_ID: data-test-terraform
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}  

    - name: Install Docker Dependencies
      run: npm ci      

    - name: Build Docker Container
      run: npm run build

    - name: Authenticate to Google Cloud
      run: gcloud auth activate-service-account deployment@datapm-test-terraform.iam.gserviceaccount.com --key-file=gcloud.key

    - name: Authorize Docker
      run: gcloud auth configure-docker --quiet

    - name: Deploy Assets
      run: npm run deploy
      env:
        PROJECT_ID: data-test-terraform
        GOOGLE_CREDENTIALS: ~/gcloud.key

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1     

    - name: Terraform Init
      run: terraform init
      env:
        PROJECT_ID: data-test-terraform
        GOOGLE_CREDENTIALS: gcloud.key 

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
      env:
        PROJECT_ID: data-test-terraform
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}} 

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        PROJECT_ID: data-test-terraform
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}} 

    - name: Google Run Update
      run: gcloud run deploy datapm-registry --project datapm-test-terraform --image gcr.io/datapm-test-terraform/datapm-registry --region us-central1 --platform managed
      env:
        PROJECT_ID: data-test-terraform
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

    - name: Publish Apollo Graphql Update
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: npx apollo service:push --graph=datapm --key=${{secrets.APOLLO_KEY}} --variant=test --localSchemaFile=backend/node_modules/datapm-lib/schema.gql
      